{"name": "test1", "status": "failed", "statusDetails": {"message": "AssertionError: assert 1 == '1'", "trace": "self = <py_test.TestCase object at 0x000002F1838F5320>\n\n    def test1(self):\n        print(\"第一条用例\")\n>       assert 1=='1'\nE       AssertionError: assert 1 == '1'\n\nscripts\\py_test.py:18: AssertionError"}, "start": 1625558636806, "stop": 1625558636806, "uuid": "980b0486-bca2-4ad5-aca3-a7ca2a6c5eba", "historyId": "d8eab8f50b948e3b8abcb17112ce06bd", "testCaseId": "0a461d82e308f843ceb6f83c24568a90", "fullName": "scripts.py_test.TestCase#test1", "labels": [{"name": "parentSuite", "value": "scripts"}, {"name": "suite", "value": "py_test"}, {"name": "subSuite", "value": "TestCase"}, {"name": "host", "value": "LAPTOP-TNIA2CIB"}, {"name": "thread", "value": "16228-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "scripts.py_test"}]}